FROM jc21/nginx-proxy-manager:2.16.0@sha256:57d85bffc776c01909c7b24e127a69a72b7d8c75d387e6cb26c762978fc43e4c

ARG BUILD_COMMIT
ARG BUILD_DATE
ENV NPM_BUILD_VERSION="2.16.0" \
	NPM_BUILD_COMMIT="${BUILD_COMMIT}" \
	NPM_BUILD_DATE="${BUILD_DATE}"
LABEL org.opencontainers.image.source="https://github.com/lennondotw/nginx-proxy-manager" \
	org.opencontainers.image.version="2.16.0-public-ports.2" \
	org.opencontainers.image.revision="${BUILD_COMMIT}"

RUN rm -rf /app
COPY backend /app
COPY frontend/dist /app/frontend
COPY docker/rootfs /
WORKDIR /app
RUN yarn install --frozen-lockfile --production \
	&& yarn cache clean \
	&& rm -rf /etc/s6-overlay/s6-rc.d/user/contents.d/frontend /etc/nginx/conf.d/dev.conf \
	&& chmod 644 /etc/logrotate.d/nginx-proxy-manager
